version: 2

sources:
  - name: "mock_data"
    meta:
      external_location: "./sources/people.xlsx"
    tables:
      - name: people

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: total_income
    description: "A starter dbt model"
    columns:
      - name: total_income
        tests:
          - not_null
