version: 2

sources:
- name: test_data
  schema: default
  tables:
  - name: sheet1
    external:
      location: "data/test-data.xlsx"
      using: excel
      options:
        dataAddress: "Sheet1!A1:C6"
        header: true
    columns:
    - name: Col1
      data_type: string
    - name: Col2
      data_type: integer
    - name: Col3
      data_type: numeric
